{% set name = "jina-hubble-sdk" %}
{% set version = "0.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jina-hubble-sdk-{{ version }}.tar.gz
  sha256: a2b85a719b0063f19dd9965043ce68a819357c38c6fb24947e6b720f18638798

build:
  entry_points:
    - jina-auth=hubble.__main__:main
    - docker-credential-jina-hubble=hubble.dockerauth:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=18.0
    - wheel
    - pip
  run:
    - python >=3.7
    - requests
    - aiohttp
    - rich
    - importlib-metadata

test:
  imports:
    - hubble
  commands:
    - pip check
    - jina-auth --help
    - docker-credential-jina-hubble --help
  requires:
    - pip

about:
  home: https://github.com/jina-ai/jina-hubble-sdk/
  summary: SDK for Hubble API at Jina AI.
  dev_url: https://github.com/jina-ai/jina-hubble-sdk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mapleeit
    - nomagick
    - delgermurun
    - Andrei997
    - floralatin
