{% set name = "jina-hubble-sdk" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jina-hubble-sdk-{{ version }}.tar.gz
  sha256: 524d7dc3feb6e77e23608c65a353a8c5a6f828d8a743c2f5e4886d7ad7eb844d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=18.0
    - wheel
    - pip
  run:
    - python >=3.7
    - requests ==2.27.1
    - aiohttp ==3.8.1
    - rich >=12.0.0

test:
  imports:
    - hubble
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jina-ai/jina-hubble-sdk/
  summary: SDK for Hubble API at Jina AI.
  dev_url: https://github.com/jina-ai/jina-hubble-sdk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mapleeit
    - nomagick
    - delgermurun
    - Andrei997
    - floralatin
