{% set name = "jina-hubble-sdk" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jina-hubble-sdk-{{ version }}.tar.gz
  sha256: 8c1f387255e0ed0ecced0df91cb89309d981e53dc3e388b5736c3c18118d9d0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=18.0
    - wheel
    - pip
  run:
    - python >=3.7
    - requests ==2.27.1
    - aiohttp ==3.8.1
    - rich >=12.0.0
    - nest-asyncio >=1.5.5

test:
  imports:
    - hubble
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jina-ai/jina-hubble-sdk/
  summary: SDK for Hubble API at Jina AI.
  dev_url: https://github.com/jina-ai/jina-hubble-sdk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mapleeit
    - nomagick
    - delgermurun
    - Andrei997
    - floralatin
